server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
  mvc:
    cors:
      enabled: true
    mapping:
      /**:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600

# JWT配置
jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDi69Ccy/27lDRc
    ip6kMiMgL0WS3A0SC/HKUciBz72EDMW2bz8dsigKGojUaih4itdPhCArdxPStu4R
    YzXsnyajbc+itK9OtKhUJQnjztCd7BUJyWR4BCq1fSIl1uu297AuyyAcOBYg/vhx
    I8Y/pTXmDigtMAZ26cw3NnMmmkV27TOF+STEK1aAhlB1+/5/tVyy/vpZC58jHVL9
    7HaqlubSi46c0rRxD1W1KwHJZmG6tGazs5wHVtl8m4ek1EuOYWu/TJm3rRATKjGy
    sAX6I3ZpjDJTQyrnZ1C9gWv+Sc5zvbPbqQLS2doIX/LmJQilzT9KLc7j7v2qYglj
    H1YXR7HtAgMBAAECggEAAsU5YbUpddTuiXFCNYezLBWes7Xc7qscqeqE+Y8lm0yC
    3FBAvn6CcrZpGaWD6EFS99zMAxvWOVwT5vTDFWqrhksHCbsiRhBmA/KTftq1+qy4
    wLZvacbk2KvpRNtROz3eLhschCsKpfYo3FaDmAabkxdBjmT0yX0IW+rEOV+qy+wK
    rYg+8AY/EaUvi3vT68UGDhhNEOYINx09u67lu1AScYelWBtGlvsR3CWX2V39qAU4
    In+HZAZw8gQJW8a55PuIItgdoXiAazqbprQ1WMnvmfyJkYXp8qEzAqe6l20+UCZN
    74k/C79bt36gchfRUw015BqmIGoSRKfiW3/3/BO49QKBgQDxnA0c65a8qIX2dVkJ
    F1brSjRlmHI9Do5cj/FMoTbLLzHfU3twJt0ja0fAImfgd5eAVbOmwdfpy15VdYIu
    hJaU4FXB8EO22KpiiUFzU4jiacHbYxsI+gLeqBqcxstEWP1cxV7MOtFS7PJEs+f7
    6bq8Kw0K+ub1dIip9DbU+xpiYwKBgQDwb80wxwOLEjCG1mlg6ZIJdrrM/LtGP7VU
    MyN5MILA6XFCvE/+AqLBXagUVY9b4Bh14rvlIo9GrOtIpDD7byHG8e1ccrxG7IMP
    VYCTiOYJ6Dkbze8YKuq5G7sBgHh3gthmHKF2qb6ZKT4q4A31w/oMPfB7KJZYje2N
    Fs3lSqajbwKBgBPKLGjKAzbAtvhQ9FICT2RGV7RaoEDQCGkcgS89pTdPTk50kA/H
    nyVfjCj4qHmCUi541pY6Gm1T8w4c6eTVh1/6YAvamjFH3ezkQTApD3U8JFzL6VL6
    53FFY6ijv9KBV39Zy0H/L1YTgmSON9oyctEm1ZKoqnJAcVE6Z6NaTfbxAoGAToHC
    9xVUc9l5nN1vxSQe+hYZgotXPuXYeGjGQXD0kLbos4i3edI0gHzrP9B8Idy3P+7L
    uVKig8o8fRiXodG0rrgZ7+DK10GsvZoGhKXjrwJzez+vvS1uPQjv89qV+zfvHtBk
    bFGamXodAXTtOf1GrS6gUiZ7iOi20yXKDv9kD+MCgYEAuOA04jeUcKokEl3rO5qV
    tDYu/LpOdJNWI5SEQp4TzK5GIQeS4X0ATivzrPKhmzuscqdzpCvXuXS12L9wBacZ
    +FX2mDqTDmpJcKU88uYC2DEvB8wBpps2IKCsgOUPIfBkqvS+K7T6XE7kt0BiMT0j
    427g8dXkXGuH08zb3BgTugI=
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4uvQnMv9u5Q0XIqepDIj
    IC9FktwNEgvxylHIgc+9hAzFtm8/HbIoChqI1GooeIrXT4QgK3cT0rbuEWM17J8m
    o23PorSvTrSoVCUJ487QnewVCclkeAQqtX0iJdbrtvewLssgHDgWIP74cSPGP6U1
    5g4oLTAGdunMNzZzJppFdu0zhfkkxCtWgIZQdfv+f7Vcsv76WQufIx1S/ex2qpbm
    0ouOnNK0cQ9VtSsByWZhurRms7OcB1bZfJuHpNRLjmFrv0yZt60QEyoxsrAF+iN2
    aYwyU0Mq52dQvYFr/knOc72z26kC0tnaCF/y5iUIpc0/Si3O4+79qmIJYx9WF0ex
    7QIDAQAB
    -----END PUBLIC KEY-----
  clock-skew: 60

spring:
  application:
    name: user-center
  ai:
    mcp:
      enabled: true